# GitHub Pages Configuration
title: "2026CT Web Development Task - Student Feedback"
description: "Comprehensive feedback for Year 9 students' Flask web development projects from the 2026 Computing Technology course"
baseurl: "/2026CT_Web_Feedback"
url: "https://tempehs.github.io"

# Theme
theme: minima

# Markdown settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO and social
author: "TempeHS TAS Faculty"

# Exclude all student directories and files to avoid Liquid processing conflicts
exclude:
  - .git/
  - .gitignore
  - .gitattributes
  - .venv/
  - .vscode/
  - .devcontainer/
  - requirements.txt
  - LICENSE
  - Bryan.H/
  - Connor.K/
  - Dan.O/
  - Daniel.L/
  - Daniel.SDLF/
  - douglas.p/
  - Isaac.j/
  - Jamie.L/
  - Jonathan.I/
  - Khoi.C/
  - Matthew.C/
  - Matthew.W/
  - Rad.A/
  - Samuel.H/
  - SebK/
  - Toby.J/
  - Tommy.D/
  - Wolfgang/
  - Zach.B/
  - _plugins/
  - _layouts/

# Only include the main README and Jekyll files
include:
  - README.md
  - index.md

# Default layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
