# GitHub Pages Configuration
title: "2026CT Web Development Task - Student Feedback"
description: "Comprehensive feedback for Year 9 students' Flask web development projects from the 2026 Computing Technology course"
baseurl: "/2026CT_Web_Feedback"
url: "https://tempehs.github.io"

# Theme
theme: minima

# Markdown settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO and social
author: "TempeHS TAS Faculty"
# This config will be overridden by the GitHub Action
# The action creates its own minimal config that only processes README.md
