# GitHub Pages Configuration
title: "2026CT Web Development Task - Student Feedback"
description: "Comprehensive feedback for Year 9 students' Flask web development projects from the 2026 Computing Technology course"
baseurl: "/2026CT_Web_Feedback"
url: "https://tempehs.github.io"

# Theme
theme: minima

# Markdown settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO and social
author: "TempeHS TAS Faculty"

# Exclude files that shouldn't be processed by Jekyll
exclude:
  - .git/
  - .gitignore
  - .gitattributes
  - .venv/
  - .vscode/
  - .devcontainer/
  - requirements.txt
  - LICENSE
  - _plugins/

# Default layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "*/feedback.md"
    values:
      layout: "feedback"
